### ISSUE TITLE
Update to .NET 6

### ISSUE THREAD

**Issue by skoruba** [skoruba/Duende.IdentityServer.Admin#37]
Related - https://github.com/skoruba/IdentityServer4.Admin/pull/928

**Comment by cjaliaga** [comment]
@skoruba sorry for hijacking this issue :) Will this update to .NET 6 also come to an update to Duende Identity Server v6? Since now the community license of Duende Identity Server v6 has removed the limitations (including the 5 max clients), more people will upgrade from Identity Server v4 to Duende Identity Server v6. Do you know if moving from our Identity Server Admin to Duende Identity Server Admin project is feasible?

Thanks as always!!

**Comment by skoruba** [comment]
Hi @cjaliaga - sure, I will update this PR #44 with IS v6, I will do it during the next week. 

You can definitely update from IS4 Admin to Duende IS Admin - I want to write some guide - how to migrate it. 😊

Thanks for your feedback!

**Comment by skoruba** [comment]
Done.
